# Generated by Django 4.1.7 on 2023-03-15 05:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(max_length=255, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Recipe ingredients'),
        ),
    ]
