# Generated by Django 4.1.7 on 2023-07-13 11:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_picture',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
